In [ ]:
import numpy as np

In [ ]:
arr= np.array([1,2,3])

In [ ]:
arr.ndim

1

In [ ]:
a=np.array([[]])
a.ndim

2

In [ ]:
range=np.arange(0,10)

In [ ]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
space=np.linspace(0,1,5)
space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
log=np.logspace(1,3,2)
log

array([  10., 1000.])

In [ ]:
zeero=np.zeros([2,3])
zeero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one=np.ones([4,3], dtype = int)
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
fulls=np.full([10,2], 10)
fulls

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [ ]:
empty = np.empty([4,5])
empty

array([[ 4.85660552e-315,  0.00000000e+000,  1.61346343e-050,
        -2.05139327e+150,  1.87793443e+027],
       [-2.67515795e-115,  3.22693070e-213, -4.97888548e-265,
         3.71309199e-212,  1.32765280e-202],
       [-9.77251718e+088, -1.19198697e-226, -7.82672187e-193,
        -3.35199312e+084, -2.84554280e-269],
       [ 4.80230856e-277,  1.56601252e+239,  9.06092203e-312,
         0.00000000e+000,  0.00000000e+000]])

In [ ]:
Arr = np.random.rand(10)
Arr

array([0.34789286, 0.62490365, 0.22674689, 0.65330272, 0.67577084,
       0.38169782, 0.27864122, 0.17406246, 0.17977425, 0.04278644])

In [ ]:
Arr = np.random.rand(2,3)
Arr

array([[0.04813812, 0.20575676, 0.01413083],
       [0.87308468, 0.92051476, 0.82647091]])

In [ ]:
Arr = np.random.randn(2,3)
Arr

array([[-1.26407827, -0.04124768,  2.09463746],
       [ 0.1764363 ,  0.76947845,  0.07039832]])

In [ ]:
Arr = np.random.randint(10,100)
Arr

47

In [ ]:
Arr = np.random.rand(10,100)
Arr

array([[0.14280857, 0.84858385, 0.57605915, 0.73404183, 0.4251576 ,
        0.85154984, 0.86478232, 0.46774355, 0.1903577 , 0.55807108,
        0.49245791, 0.22687739, 0.01731593, 0.60680819, 0.16711926,
        0.75553663, 0.3567559 , 0.23046642, 0.72983489, 0.43323093,
        0.78820795, 0.32540278, 0.29341541, 0.59792884, 0.88128829,
        0.82101749, 0.6862428 , 0.06552303, 0.21297892, 0.85242614,
        0.81038592, 0.30014134, 0.8512486 , 0.29200777, 0.85635526,
        0.13462815, 0.49001309, 0.1483332 , 0.71927884, 0.11707089,
        0.01722888, 0.33178773, 0.27568201, 0.26128459, 0.19290411,
        0.86046127, 0.10989521, 0.20001019, 0.60085907, 0.93740235,
        0.11323237, 0.99088961, 0.46029259, 0.06446762, 0.52062461,
        0.71598956, 0.19272255, 0.44488292, 0.21168402, 0.69773043,
        0.06479746, 0.87950621, 0.06642264, 0.1119836 , 0.36140607,
        0.14690042, 0.72026542, 0.11380364, 0.63189687, 0.5639015 ,
        0.53697972, 0.2532244 , 0.1732257 , 0.19

In [ ]:
arr=np.random.randint(10,100,size=(2,3))
arr

array([[33, 53, 63],
       [76, 82, 37]])

In [ ]:
import numpy as np
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst=["string",1,2,3,45.6]
arr=np.array(lst)
arr

array(['string', '1', '2', '3', '45.6'], dtype='<U32')

In [ ]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1,2,3,4],dtype=np.float64)
arr

array([1., 2., 3., 4.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
new_arr=arr.astype(np.float64)
new_arr

array([1., 2., 3., 4.])

In [ ]:
new_arr2=new_arr.astype(np.int64)
new_arr2

array([1, 2, 3, 4])

In [ ]:
arr =np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim


2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

In [ ]:
arr=np.array([1,3,5,6,7,8])
reshape=arr.reshape(3,2)
reshape

array([[1, 3],
       [5, 6],
       [7, 8]])

In [ ]:
ravel= reshape.ravel()
ravel

array([1, 3, 5, 6, 7, 8])

In [ ]:
ravel[0]=300
ravel

array([300,   3,   5,   6,   7,   8])

In [ ]:
flat=ravel.flatten()
flat

array([300,   3,   5,   6,   7,   8])

In [ ]:
flat[0]=1
flat

array([1, 3, 5, 6, 7, 8])

In [ ]:
ravel

array([300,   3,   5,   6,   7,   8])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,7,6,8])

In [ ]:
a+b

array([ 6,  9,  9, 12])

In [ ]:
a-b

array([-4, -5, -3, -4])

In [ ]:
b-a

array([4, 5, 3, 4])

In [ ]:
a/b

array([0.2       , 0.28571429, 0.5       , 0.5       ])

In [ ]:
a*b



array([ 5, 14, 18, 32])

In [ ]:
a**b

array([    1,   128,   729, 65536])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4,5,6,7]

In [ ]:
a[0]

1

In [ ]:
a[-1]

7

In [ ]:
a[0:6]

[1, 2, 3, 4, 5, 6]

In [ ]:
a[-1:-7:-1]

[7, 6, 5, 4, 3, 2]

In [ ]:
a[  : : 2]

[1, 3, 5, 7]

In [ ]:
arr = np.array([10,20,30,40,50])

In [ ]:
arr[::-2]

array([50, 30, 10])

In [ ]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1:3,1:9]

array([[5, 6],
       [8, 9]])

In [ ]:
arr = np.array([10,20,30,40,50])
ind=[0,2]
np.take(arr,ind)

array([10, 30])

In [ ]:
arr=np.array([[1,2],[3,4]])


In [ ]:
for x in np.nditer(arr):
  print(x,end=" ")

1 2 3 4 

In [ ]:
for ind, x in np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
arr = np.array([1,2,3,5,6])
view = arr[1:5]
view

array([2, 3, 5, 6])

In [ ]:
view[0]=300

In [ ]:
view

array([300,   3,   5,   6])

In [ ]:
cp=arr[0:5].copy()
cp

array([  1, 300,   3,   5,   6])

In [ ]:
cp[1]=2
cp

array([1, 2, 3, 5, 6])

In [ ]:
arr

array([  1, 300,   3,   5,   6])

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2],[4,5]])
arr

array([[1, 2],
       [4, 5]])

In [ ]:
print(arr.transpose())

[[1 4]
 [2 5]]


In [ ]:
arr = np.array([[[1,2],[4,5]]])
arr.shape

(1, 2, 2)

In [ ]:
swap= np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

In [ ]:
arr=np.array([1,2,3])
arr_2=np.array([4,5,6])
combine=np.concatenate((arr,arr_2))
combine




array([1, 2, 3, 4, 5, 6])

In [ ]:
combine=np.concatenate((arr,arr_2))
combine

array([1, 2, 3, 4, 5, 6])

In [ ]:
combine=np.concatenate((arr,arr_2))
combine

array([1, 2, 3, 4, 5, 6])

In [ ]:
combine=np.concatenate((arr,arr_2))
combine

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr_1=np.array([[1,2],[2,3]])
arr_2=np.array([[4,5],[6,7]])
print(np.vstack((arr_1,arr_2)))

[[1 2]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
print(np.stack((arr_1,arr_2),axis=0))

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
arr_1=np.array([[1,2],[2,3]])
arr_2=np.array([[4,5],[6,7]])
print(np.hstack((arr_1,arr_2)))

[[1 2 4 5]
 [2 3 6 7]]


In [ ]:
print(np.stack((arr_1,arr_2),axis=1))

[[[1 2]
  [4 5]]

 [[2 3]
  [6 7]]]


In [ ]:
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(arr,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
arr=np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
arr=np.array([1,2,3,4,5])
print(np.tile(arr,2))

[1 2 3 4 5 1 2 3 4 5]


In [ ]:
arr=np.array([3,4,5,6])
print(np.sum(arr))

18


In [ ]:
arr=np.array([3,4,5,6])
print(np.mean(arr))

4.5


In [ ]:
arr=np.array([3,4,5,6])
print(np.median(arr))

4.5


In [ ]:
print(np.std(arr)) #stander deviantion
print(np.min (arr))  #min value
print(np.max(arr))# max value


1.118033988749895
3
6


In [ ]:
print(np.cumsum(arr))

[ 3  7 12 18]


In [ ]:
print(np.cumprod(arr))

[  3  12  60 360]


In [ ]:
arr


array([3, 4, 5, 6])

In [ ]:
result=np.where(arr<4,"low","high")
result

array(['low', 'high', 'high', 'high'], dtype='<U4')

In [ ]:
print(np.argwhere(arr>3))

[[1]
 [2]
 [3]]


In [ ]:
arr = np.array([20,30,40,50])
mask=np.logical_and(arr>15,arr<35)
mask

array([ True,  True, False, False])

In [ ]:
arr

array([20, 30, 40, 50])

In [ ]:
mask =np.logical_and(arr>30,arr<50)
mask

array([False, False,  True, False])

In [ ]:
arr = np.array([20,30,40,50])
mask =np.logical_or(arr>30,arr<50)
mask


array([ True,  True,  True,  True])

In [ ]:
arr= np.array([0,1,0,3,4,5])
print(np.nonzero(arr))

(array([1, 3, 4, 5]),)


In [ ]:
image=np.array([[200,250],[300,350],[400,450]])
brigtness=image+50
brigtness

array([[250, 300],
       [350, 400],
       [450, 500]])

In [ ]:
arr=np.array([2,3,4,5,6])
def square(x):
  return x*x
vfun=np.vectorize(square)
print(vfun(arr))

[ 4  9 16 25 36]


In [ ]:
arr

array([0, 1, 0, 3, 4, 5])

In [ ]:
print(vfun(arr_2))

[[16 25]
 [36 49]]


In [ ]:
arr

array([2, 3, 4, 5, 6])

In [ ]:
a=np.array([1.,2.,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [ ]:
a=np.array([1.,2.,np.nan,4])
print(np.isnan(a))

[False False  True False]


In [ ]:
b= np.array([1,np.nan,np.inf,10.2,40])
print(np.isinf(b))

[False False  True False False]


In [ ]:
b= np.array([1,np.nan,np.inf,10.2,40])
new_b=np.nan_to_num(b)
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])

In [ ]:
git init


SyntaxError: invalid syntax (3277417328.py, line 1)